# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c7517001d94b6afa3a5d019800a40aba6b864b28555485907f4f2518614d9cc163504a9d1a4e06f37fa4e72c1070841100588786c0394f42e84062f9551ea7c

test:
  secret_key_base: 81521559abb53f577cc63a3b366d45f0acbde1b6612f5a33b817df15be184b3f82f94508135a8900338e37f8eaf522aba8a95ced8d353208c5d30cdfd4eafbfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
